### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [sailajasumana/prj-rev-bwfs-dasmoto#4]
For properties shared among multiple elements such as `font-weight: bold;`, you could use comma-separated selectors to specify them all at once.

```css
h1, h2, h3 {
  font-weight: bold;
}
```
